Project/config/routes.rb
Rails.application.routes.draw do


  root "games#index"
  get '/user', to: 'user#index'
  get 'games/search', to: 'games#search', as: :search_games
  get 'games/details/:id', to: 'games#details', as: :details_game
  get 'games/store_lowest_prices', to: 'games#store_lowest_prices'
  get '/collections', to: 'collections#index'
  post 'games/add_to_collection', to: 'games#add_to_collection', as: :add_to_collection_game


  get '/my_comments', to: 'user#user_comments', as: 'user_comments'

 #  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'


 # support page routes 
  # Add a route for the new action (displaying the contact form)
  get '/support', to: 'support#new', as: :new_support

  # Add a route for the create action (processing the form submission)
  post '/support', to: 'support#create', as: :create_support


  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }  


  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end 

  resources :deals

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
  end

  resources :collections, only: [:index, :new, :create, :destroy]

  resources :game_collections, only: [:create, :destroy] 

  resources :games do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
    member do
      post 'add_to_collection'
    end
  end

  namespace :admins do
        resources :users, only: [:index, :destroy] do 
         member do
      put 'ban'
      put 'unban'
      put 'temporary_ban'
      put 'make_admin'
      put 'revoke_admin'
    end
  end
    get 'index', to: 'users#index', as: :index
    get 'destroy', to: 'users#destroy', as: :destroy
    end
end

Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <style>
    .button-link {
      padding: 7px;
      background-color: #4285f4;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
    }

    .button-login {
      padding: 7px;
      background-color: teal;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
    }

    .top-nav {
      background-color: lightblue;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px;
    }
  </style>

   <head>
       <nav class="top-nav">
        <div style="width: 25%; text-align: left;">
          <%= link_to "GameSalesTracker", root_path, class: "button-link" %><br><br>
          <%= link_to "My Wishlist", support_path, class: "button-link" %>
        </div>
        <div style="width: 50%; text-align: center;">
          <% if user_signed_in? %>
            Welcome back, <%= current_user.email%>! [<%= link_to 'Logout', destroy_user_session_path, :method => :delete%>]
          <% else %>
        <!-- Content for non-logged-in users -->
            New here? <%= link_to "Sign Up", new_user_registration_path, class: "button-login" %>
          <% end %>
          <br><br>
      <%= form_with url: search_games_path, method: :get do |f| %>
        <%= f.label :game_name, "Nome del gioco" %>
        <%= f.text_field :game_name %>
        <%= f.submit "Cerca" %>
      <% end %>
      </div>
      <div style="width: 25%; text-align: right;">
      <% if user_signed_in? %>
        <%= link_to "My account", root_path, class: "button-link" %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "button-link" %>
      <% end %>
      <br><br>
        <%= link_to "Support", support_path, class: "button-link" %>
      </div>
    </nav>
   <% flash.each do |type, msg| %> <div>
    Notification: <%= msg %>
  </div>
<% end %>
    <title>GameSalesTracker.com</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
  <br><br>
</html>

<%= link_to "Need help?", support_path %>

Project/app/views/layouts/navbar_layout.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= stylesheet_link_tag 'profile', media: 'all' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

  <nav class="top-nav">

    <div style="width: 40%;">
      <div class="button-container-left">
        <%= link_to "GameSalesTracker", root_path, class: "button-link" %>
        <%= form_with url: search_games_path, method: :get do |f| %>
        <div class="search">
          <%= f.text_field :search_query, class: "searchTerm", placeholder: "Search for games" %>
          <button type="submit" class="searchButton">
            <i class="fas fa-search"></i>
          </button>
        </div>
        <% end %>
      </div>
    </div>

<div style="width: 60%;">
  <div class="button-container-right">
    <% if user_signed_in? %>
      <div class="dropdown" style="padding: 7px;">
        <a class="button-link dropdown-toggle" href="#" role="button" id="accountDropdown" data-bs-toggle="dropdown" aria-expanded="false">
          My Account
        </a>
        <ul class="dropdown-menu" aria-labelledby="accountDropdown">
          <li><%= link_to 'My Profile', user_path(current_user), class: 'dropdown-item' %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'%></li>

          <% if current_user.role == 'admin' %>
            <li class="dropdown-divider"></li>
            <li><%= link_to 'Admin panel', admins_index_path, class: 'dropdown-item' %></li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'button-link' %>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'button-link' %>
    <% end %>

    <%= link_to 'Need Help?', new_support_path, class: 'button-link' %>
  </div>
</div>


  </nav>

  <title>GameSalesTracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body data-turbo-action="replace">
  <%= yield %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>