Project/config/routes.rb
Rails.application.routes.draw do


  root "games#index"
  get '/user', to: 'user#index'
  get 'games/search', to: 'games#search', as: :search_games
  get 'games/details/:id', to: 'games#details', as: :details_game
  get 'games/store_lowest_prices', to: 'games#store_lowest_prices'
  get '/collections', to: 'collections#index'
  post 'games/add_to_collection', to: 'games#add_to_collection', as: :add_to_collection_game


  get '/my_comments', to: 'user#user_comments', as: 'user_comments'

 #  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'


 # support page routes 
  # Add a route for the new action (displaying the contact form)
  get '/support', to: 'support#new', as: :new_support

  # Add a route for the create action (processing the form submission)
  post '/support', to: 'support#create', as: :create_support


  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }  


  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end 

  resources :deals

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
  end

  resources :collections, only: [:index, :new, :create, :destroy]

  resources :game_collections, only: [:create, :destroy] 

  resources :games do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
    member do
      post 'add_to_collection'
    end
  end

  namespace :admins do
        resources :users, only: [:index, :destroy] do 
         member do
      put 'ban'
      put 'unban'
      put 'temporary_ban'
      put 'make_admin'
      put 'revoke_admin'
    end
  end
    get 'index', to: 'users#index', as: :index
    get 'destroy', to: 'users#destroy', as: :destroy
    end
end

Project/app/models/game.rb
class Game < ApplicationRecord
    include Visible
    has_many :game_collections
    has_many :collections, through: :game_collections

    validates :plain, uniqueness: true
    validates :title, presence: true
    validates :body, presence: true, length: {minimum: 10}

    def available_collections(user)
        user.collections.where.not(id: self.collection_ids)
    end
end

Project/app/controllers/games_controller.rb
class GamesController < ApplicationController
  require 'httparty'
  require 'cgi'
  include GamesHelper
  include SharedHelper
  layout 'navbar_layout'
  before_action :set_api_key
  before_action :authenticate_user!, except: [:index, :show, :search, :details_game]

  def index
    cache_key = "games_index_#{params[:page]}_#{params[:sort]}"
    @games = Rails.cache.fetch('games_index', expires_in: 20.minutes) do
    end
    @deals = get_deals
    @lastdeals = Rails.cache.fetch('last_deals', expires_in: 20.minutes) do
      get_last_deals
    end
  end

  def search
    if params[:search_query].present?
      @search_query = params[:search_query]
      cache_key = "search_results_#{@search_query}_#{params[:page]}_#{params[:sort]}"
      @games = Rails.cache.fetch(cache_key, expires_in: 20.minutes) do
        search_games(@search_query, capacity: 1)
      end
      @games.each do |game|
        game['prices'] = get_game_prices(game['id'], capacity: 1)
      end
    else
      @games = []
    end
  end

  def details
    @game_id = params[:id]
  
    begin
      @game_details = get_game_details(@game_id)
      puts @game_details.inspect
      @game_prices = get_game_prices(@game_id)  # Non specificare capacity per ottenere tutti i prezzi      @lowest_price = get_lowest_price(game_id)
  
      @game_plain = @game_details['slug']
      @comments = Comment.where(gameplain: @game_id)
    rescue StandardError => e
      flash[:error] = "Errore nel recupero dei dettagli del gioco: #{e.message}"
      @game_details = nil
      @game_prices = nil
      @lowest_price = nil
    end
  
    @game_collection = current_user.collections.new
  end  

  def add_to_collection
    game_id = params[:game_id]
    collection_id = params[:collection_id]
  
    if collection_id.present?
      if Collection.exists?(collection_id)
        game_collection = GameCollection.find_by(game_id: game_id, collection_id: collection_id)
  
        if game_collection.nil?
          game_collection = GameCollection.new(game_id: game_id, collection_id: collection_id)
  
          if game_collection.save
            flash[:notice] = 'Game added to collection successfully.'
          else
            flash[:error] = 'Failed to add game to collection.'
          end
        else
          flash[:error] = 'Game is already in the collection.'
        end
      else
        flash[:error] = 'Invalid collection.'
      end
    else
      flash[:error] = 'Invalid collection.'
    end
  
    redirect_back fallback_location: root_path
  end
  
  
  
  

  private

  def set_api_key
    @api_key = 'b14274e8092bc14e227b32e4b66c2903bf4419c9'
  end
  
  def get_last_deals
    Rails.cache.fetch('last_deals', expires_in: 20.minutes) do
    limit = 18  
    offset= 3000
    url = "https://api.isthereanydeal.com/deals/v2?key=#{@api_key}"
    url += "&country=US"
    url += "&offset=#{offset}"
    url += "&limit=#{limit}"  
    url += "&sort=expiry"
    
    begin
      response = RestClient.get(url)
      puts "API Response (Last Deals): #{response.body}"
      parsed_response = JSON.parse(response)
      deals_data = parsed_response['list']
  
      # Per ogni deal, ottieni i dettagli completi del gioco
      deals_data.each do |deal|
        game_id = deal['id']
        game_details = get_game_details(game_id)
        # Aggiungi i dettagli del gioco al deal
        deal['game_details'] = game_details
      end
  
      return deals_data if deals_data.present?
    rescue RestClient::ExceptionWithResponse => e
      puts "Errore nella richiesta dei Last Deals: #{e.response}"
    rescue => e
      puts "Errore nella richiesta dei Last Deals: #{e.message}"
    end
    
    return []
  end
  end
  

  def get_deals
    url = "https://api.isthereanydeal.com/deals/v2?key=#{@api_key}"
    url += "&country=US"
    url += "&offset=#{params[:offset]}" if params[:offset].present?
    url += "&limit=#{params[:limit]}" if params[:limit].present?
    url += "&sort=#{params[:sort]}" if params[:sort].present?
    url += "&shops=#{params[:shops].join(',')}" if params[:shops].present?
    url += "&filter=#{params[:filter]}" if params[:filter].present?
  
    begin
      response = RestClient.get(url)
      puts "API Response (Deals): #{response.body}"  # Stampa la risposta nel terminale
      parsed_response = JSON.parse(response)
      deals_data = parsed_response['list']
       # Per ogni deal, ottieni i dettagli completi del gioco
       deals_data.each do |deal|
        game_id = deal['id']
        game_details = get_game_details(game_id)
        # Aggiungi i dettagli del gioco al deal
        deal['game_details'] = game_details
      end
  
      return deals_data if deals_data.present?
    rescue RestClient::ExceptionWithResponse => e
      puts "Errore nella richiesta dei Last Deals: #{e.response}"
    rescue => e
      puts "Errore nella richiesta dei Last Deals: #{e.message}"
    end
    
    return []
end
    
  def search_games(query, capacity: nil, page: nil, sort: nil)
    cache_key = "search_games_#{CGI.escape(query)}_#{page}_#{sort}"
    games = Rails.cache.fetch(cache_key, expires_in: 20.minutes) do
    url = "https://api.isthereanydeal.com/games/search/v1?key=#{@api_key}&title=#{CGI.escape(query)}"    
    url += "&capacity=#{capacity}" if capacity.present?
    response = HTTParty.get(url)

    if response.success?
      games = JSON.parse(response.body)
      games.map do |game|
        {
          'id' => game['id'],
          'slug' => game['slug'],
          'title' => game['title'],
          'type' => game['type'],
          'mature' => game['mature']
        }
      end
    else
      # Gestione degli errori, ad esempio restituendo un array vuoto
      []
    end
  end
  games
  end
  

  def get_game_details(id)
    details_url = "https://api.isthereanydeal.com/games/info/v2?key=#{@api_key}&id=#{id}"
  
    response = RestClient.get(details_url)
    parsed_response = JSON.parse(response)
    puts "Dettagli del gioco:"
    puts parsed_response.inspect  # Aggiungi questa linea per visualizzare i dettagli del gioco nel terminale
    parsed_response
  rescue RestClient::ExceptionWithResponse => e
    puts "Errore nella richiesta di dettagli del gioco: #{e.response}"
    {}
  rescue => e
    puts "Errore nella richiesta di dettagli del gioco: #{e.message}"
    {}
  end  

  def get_lowest_price(game_plain)
    lowest_url = "https://api.isthereanydeal.com/v01/game/lowest/?key=#{@api_key}&plains=#{game_plain}"

    begin
      response = RestClient.get(lowest_url)
      parsed_response = JSON.parse(response)

      lowest_price_data = parsed_response['data'][game_plain]

      if lowest_price_data.present?
        return lowest_price_data
      else
        return {}
      end
    rescue RestClient::ExceptionWithResponse => e
      puts "Errore nella richiesta del prezzo più basso: #{e.response}"
      return {}
    rescue => e
      puts "Errore nella richiesta del prezzo più basso: #{e.message}"
      return {}
    end
  end

  def store_lowest_prices
    game_plain = params[:plain]
    key = @api_key

    response = RestClient.get "https://api.isthereanydeal.com/v01/game/storelow/?key=#{key}&plains=#{game_plain}"
    data = JSON.parse(response.body)

    @lowest_prices = data.dig('data', game_plain) || []
  end

end

Project/app/helpers/games_helper.rb
# In app/helpers/games_helper.rb

module GamesHelper
    include ActionView::Helpers::NumberHelper
    def display_price(price)
      if price.present? && price.to_f > 0
        "€#{number_with_precision(price, precision: 2)}"
      else
        'N/D'
      end
    end    
    
    def game_image_url(plain)
      game_info_url = "https://api.isthereanydeal.com/v01/game/info/?key=#{ENV['ITAD_API_KEY']}&plains=#{plain}"
      response = RestClient.get(game_info_url)
      parsed_response = JSON.parse(response)
      image_url = parsed_response.dig('data', plain, 'image')
      image_url.presence || placeholder_image_url
    rescue RestClient::ExceptionWithResponse, JSON::ParserError
      placeholder_image_url
    end    

    def game_image_tag(image_url)
      if image_url.present?
        image_tag(image_url, class: "img-thumbnail", alt: "Game Image")
      else
        image_tag(placeholder_image_url, class: "img-thumbnail", alt: "Placeholder Image")
      end
    end
    
    def placeholder_image_url
      ActionController::Base.helpers.asset_path('placeholder.png')
    end             

    def display_boolean(value)
      value.present? ? (value ? 'Yes' : 'No') : 'N/D'
    end
    
  
    def display_percent(value)
      value.present? ? "#{value}%" : 'N/D'
    end    
  
    def display_review(review)
      if review.present?
        "Steam Review: #{review['text']} (#{review['perc_positive']}% positive, #{review['total']} reviews)"
      else
        'N/D'
      end
    end
  
    def display_urls(urls)
      if urls.present?
        urls.map { |type, url| "#{type.capitalize}: #{link_to(type.capitalize, url)}" }.join(', ')
      else
        'N/D'
      end
    end

    def deal_title(deal)
      link_to deal['title'], details_game_path(plain: deal['plain'])
    end

    def formatted_price(price)
      "€ #{'%.2f' % price}" if price.present?
    end

    def formatted_time(time)
      if time.present?
        parsed_time = Time.parse(time)
        parsed_time.strftime("%Y-%m-%d %H:%M")
      else
        'Data non disponibile'
      end
    end       

    def formatted_expiry(expiry)
      expiry.present? ? Time.at(expiry).strftime("%Y-%m-%d %H:%M:%S") : 'Expiry non disponibile'
    end

    def countdown_to_end_date(end_date)
      return '--' unless end_date
      
      remaining_time = end_date.to_i - Time.now.to_i
      
      if remaining_time.negative?
        return 'ended'
      end
    
      days = remaining_time / 1.day
      hours = (remaining_time % 1.day) / 1.hour
      minutes = (remaining_time % 1.hour) / 1.minute
      seconds = remaining_time % 1.minute
    
      "#{days.to_i} d #{hours} h #{minutes} m #{seconds} s"
    end    

  def game_image_tag(image_url, options = {})
    options[:class] ||= ''
    options[:class] += ' card-img-top img-fluid'
    options[:alt] ||= 'Game Image'
    image_tag(image_url.presence || 'placeholder.png', options)
  end

  def calculate_cut(price, regular_price)
    cut = ((regular_price.to_f - price.to_f) / regular_price.to_f * 100).round(2)
    "#{cut}%"
  end

  def score_color_class(score)
    if score.present? && score >= 75
      'high-score'
    elsif score.present? && score >= 50
      'medium-score'
    elsif score.present?
      'low-score'
    else
      # Gestione nel caso in cui score sia nullo
      'default-score'
    end
  end
end
  

Project/app/views/games/_form.html.erb
<%= form_with model: game do |form| %>

<div>
<%= form.label :title %> <br>
<%= form.text_field :title %>
<% game.errors.full_messages_for(:title).each do |message| %>
<div> <%= message %></div>
<% end %>
</div>

<div>
<%= form.label :body %><br>
<%= form.text_area :body %>
<% game.errors.full_messages_for(:body).each do |message| %>
<div> <%= message %></div>
<% end %>
</div>
<div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>
<div>
<%= form.submit %>
</div>
<% end %>

Project/app/views/games/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <%= javascript_include_tag 'activestorage' %>
  <%= csrf_meta_tags %>
    <!-- Collegamento a jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Collegamento a Select2 CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet">
  <!-- Collegamento a Select2 JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vanilla-tilt@1.7.0/dist/vanilla-tilt.min.js"></script>
  <%= stylesheet_link_tag 'cards', media: 'all' %>
  <%= stylesheet_link_tag 'table', media: 'all' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>

<body>
  <!--FLASH MESSAGES/ALERT-->
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>

  <br>    
  <!-- LAST DEALS SECTION -->
<h1 class="text-light">Almost finished:</h1>
<div class="container mt-4 mb-10">
  <div id="last_deals" class="carousel slide mx-auto position-relative" style="width: 90%;" data-bs-ride="carousel" data-bs-interval="5000" data-bs-pause="false">
    <div class="carousel-inner">
      <% @lastdeals.each_slice(3).with_index do |deal_slice, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
          <div class="row">
            <% deal_slice.each do |deal| %>
              <div class="col-md-4">
                <div class="card card-tilt" data-tilt data-tilt-max="13" data-tilt-speed="100" data-tilt-glare="true" data-tilt-max-glare="0.2" scale="1">
                  <div class="vanilla-tilt-child">
                    <div class="image-container">
                    <% if deal['game_details'].is_a?(Hash) && deal['game_details']['assets'].is_a?(Hash) && deal['game_details']['assets']['banner300'].present? %>
                    <%= image_tag(deal['game_details']['assets']['banner300'], class: 'card-img-top img-fluid') %>
                      <% else %>
                        <%= image_tag('placeholder.png', class: 'card-img-top img-fluid') %>
                      <% end %>
                    </div>
                    <div class="card-body">
                      <h5 class="card-title text-center"><%= link_to details_game_path(id: deal['game_details']['id']) do %>
                        <%= deal['title'] %>
                      <% end %>
                      </h5>
                      <p class="card-text text-center">
                      <del><%= "%.2f" % deal['deal']['regular']['amount'].to_f %> €</del>
                      <% if deal['deal']['price']['amount'] == 0 %>
                        <span class="price-new fw-bold fs-3 text-success"><%= "%.2f" % deal['deal']['price']['amount'].to_f %> €</span>
                        <span class="badge bg-success">Free</span>
                      <% else %>
                        <span class="price-new fw-bold fs-3"><%= "%.2f" % deal['deal']['price']['amount'].to_f %> €</span>
                      <% end %>
                      <span class="discounted-price fw-bold fs-6">-<%= deal['deal']['cut'] %>%</span>      
                    </p>  
                    <p class="card-text text-center">
                      Ends in:
                      <% remaining_time = (Time.parse(deal['deal']['expiry']) - Time.now).to_i %>
                      <% days = remaining_time / (24 * 60 * 60) %>
                      <% hours = (remaining_time % (24 * 60 * 60)) / (60 * 60) %>
                      <% minutes = (remaining_time % (60 * 60)) / 60 %>
  
                      <% if remaining_time > 60.minutes %> 
                        <span class="text-success"><%= "#{days} d #{hours} h #{minutes} m" %></span>
                      <% elsif remaining_time > 15.minutes %>
                        <span class="text-warning"><%= "#{days} d #{hours} h #{minutes} m" %></span>
                      <% else %>
                        <span class="text-danger"><%= "#{days} d #{hours} h #{minutes} m" %></span>
                      <% end %>
                    </p>

                      <div class="card-text text-center">
                        
                      </div>
                    </div>
                  </div>
                  <div class="vanilla-tilt-glare"></div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- Aggiornare i controlli del carousel -->
    <button class="carousel-control-prev" type="button" data-bs-target="#last_deals" data-bs-slide="prev" style="left: -10%;">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#last_deals" data-bs-slide="next" style="right: -10%;">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<!-- END OF LAST DEALS SECTION -->

  <br>
  <div class="container mt-4">
    <h1 class="text-light">Deals</h1>

    <%= form_tag(games_path, method: 'get') do %>
      <div class="row">
        <div class="col-md-2">
          <%= label_tag 'limit', 'Limit:' %>
          <%= select_tag 'limit', options_for_select([20, 30, 50,100], params[:limit].to_i), class: 'form-control', id: 'limit-select' %>
        </div>
        <div class="col-md-2">
          <%= label_tag 'sort', 'Sort:' %>
          <%= select_tag 'sort', options_for_select([['Price (min)', 'price'], ['Prezzo (max)', '-price'], ['Discount (min)', 'cut'], ['Discount (max)', '-cut'],['Expiration (almost new)', 'expiry'],['Expiration (almost expired)', '-expiry']], params[:sort]), class: 'form-control', id: 'sort-select' %>
        </div>
        <div class="col-md-4">
          <%= label_tag 'shops[]', 'Shop Filter:' %>
          <%= select_tag 'shops[]', options_for_select([
            ['Tutti gli Store', nil],
            ['2game', 19],
            ['AllYouPlay', 2],
            ['Amazon', 3],
            ['Blizzard', 4],
            ['DLGamer', 13],
            ['Dreamgame', 15],
            ['EA Store', 52],
            ['Epic Game Store', 16],
            ['eTail.Market', 67],
            ['Fanatical', 6],
            ['FireFlower', 17],
            ['GameBillet', 20],
            ['GamersGate', 24],
            ['Gamesload', 25],
            ['GamesPlanet DE', 27],
            ['GamesPlanet FR', 28],
            ['GamesPlanet UK', 26],
            ['GamesPlanet US', 29],
            ['GOG', 35],
            ['GreenManGaming', 36],
            ['Humble Store', 37],
            ['IndieGala Store', 42],
            ['Itch.io', 44],
            ['JoyBuggy', 65],
            ['MacGameStore', 47],
            ['Microsoft Store', 48],
            ['Newegg', 49],
            ['Noctre', 66],
            ['Nuuvem', 50],
            ['Square Enix', 60],
            ['Steam', 61],
            ['Ubisoft Store', 62],
            ['Voidu', 63],
            ['WinGameStore', 64],
          ], params[:shops]), { multiple: true, class: 'form-control custom-select select2 shop-filter', id: 'shop-filter-select' } %>
        </div>
        <div class="col-md-2">
          <%= submit_tag 'Apply', class: 'btn btn-primary mt-4' %>
        </div>
      </div>
    <% end %>    
    <button id="toggleViewButton" class="btn btn-primary mt-4 mb-4"></button>
    <br>
    
    <div class="table-responsive" id="deal_table">
      <table class="table table-custom">
        <thead class="thead-dark">
          <tr>
            <th class="text-light">Cover</th>
            <th class="text-light">Title</th>
            <th class="text-light">Price</th>
            <th class="text-light">Regular Price</th>
            <th class="text-light">Cut</th>
            <th class="text-light">Started</th>
            <th class="text-light">Details</th>
          </tr>
        </thead>
        <tbody>
  <% @deals.each do |deal| %>
    <tr>
      <td class="text-light">
        <div class="image-container">
        <% if deal['game_details'].is_a?(Hash) && deal['game_details']['assets'].is_a?(Hash) && deal['game_details']['assets']['banner300'].is_a?(String) %>
              <%= image_tag(deal['game_details']['assets']['banner300'], class: 'card-img-top img-fluid', alt: deal['title']) %>
            <% else %>
              <%= image_tag('placeholder.png', class: 'card-img-top img-fluid', alt: deal['title']) %>
            <% end %> 
        </div>
      </td>
      <td class="text-light">
      <%= link_to details_game_path(id: deal['game_details']['id']) do %>
        <%= deal['title'] %>
      <% end %>      
      </td>
      <td class="text-light text-center price_new"><%= "%.2f" % (deal['deal']['price']['amount'].to_f || 0) %> <%= deal['deal']['price']['currency'] %></td>
      <td class="price_original"><%= "%.2f" % (deal['deal']['regular']['amount'].to_f || 0) %> <%= deal['deal']['regular']['currency'] %></td>
      <td class="price_cut"><%= deal['deal']['cut'] %> %</td>
      <td class="deal_added"><%= formatted_time(deal['deal']['timestamp']) %></td>
      <td class="text-light deal_shop">
      <% if deal['deal']['shop'].present? %>
        <%= link_to "Disponibile su #{deal['deal']['shop']['name']}", deal['deal']['url'], target: '_blank' %>
      <% else %>
        Dettagli non disponibili
      <% end %>
    </td>
      <% end %>      
</tbody>

      </table>
    </div>

    <div class="container card-cont" id="deal_cards">
  <% if @deals.present? %>
    <div class="row row-cols-1 row-cols-md-3">
      <% @deals.each do |deal| %>
        <div class="col mb-2">
          <div class="card card-tilt">
            <div class="vanilla-tilt-child">
              <div class="image-container">
              <% if deal['game_details'].is_a?(Hash) && deal['game_details']['assets'].is_a?(Hash) && deal['game_details']['assets']['banner300'].is_a?(String) %>
              <%= image_tag(deal['game_details']['assets']['banner300'], class: 'card-img-top img-fluid', alt: deal['title']) %>
            <% else %>
              <%= image_tag('placeholder.png', class: 'card-img-top img-fluid', alt: deal['title']) %>
            <% end %>            
              </div>
              <div class="card-body">
                <h5 class="card-title text-center"><%= link_to details_game_path(id: deal['game_details']['id']) do %>
                  <%= deal['title'] %>
                <% end %>
                </h5>
                <p class="card-text text-center">
                  <del><%= "%.2f" % deal['deal']['regular']['amount'].to_f %> <%= deal['deal']['regular']['currency'] %></del>
                  <% if deal['deal']['price']['amount'] == 0 %>
                    <span class="price-new fw-bold fs-3 text-success"><%= "%.2f" % deal['deal']['price']['amount'].to_f %> <%= deal['deal']['price']['currency'] %></span>
                    <span class="badge bg-success">Free</span>
                  <% else %>
                    <span class="price-new fw-bold fs-3"><%= "%.2f" % deal['deal']['price']['amount'].to_f %> <%= deal['deal']['price']['currency'] %></span>
                  <% end %>
                  <span class="discounted-price fw-bold fs-6">-<%= deal['deal']['cut'] %> %</span>      
                </p>              
                <div class="card-text text-center">
                 
                </div>
              </div>
              <div class="vanilla-tilt-glare"></div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>Risultati della ricerca:</p>
    <p>Nessun risultato trovato.</p>
  <% end %>
</div>


    <script>
     // Inizializza Select2 sulla casella di selezione multipla
      $(document).ready(function() {
        var selectElement = $('.select2');

        // Imposta il placeholder
        selectElement.attr('data-placeholder', 'Select one or more store...');

        // Inizializza Select2
        selectElement.select2();

        // Aggiunge un listener per gestire la selezione
        selectElement.on('select2:select', function (e) {
          // Rimuovi il placeholder dopo la selezione
          $(this).find('[value=""]').remove();
        });
      });

      // Inizializza Vanilla Tilt sulle carte del carosello
      document.addEventListener('DOMContentLoaded', function () {
        VanillaTilt.init(document.querySelectorAll("[data-tilt]"));
      });

      document.addEventListener('DOMContentLoaded', function () {
    // Initially hide the table and show the card view
    toggleTableView(false);

    // Set the initial button text based on the current view
    const buttonText = 'Show Table';
    document.getElementById('toggleViewButton').innerText = buttonText;

    // Add click event listener to the toggle button
    document.getElementById('toggleViewButton').addEventListener('click', function () {
        // Toggle between table and card views
        toggleTableView();
    });

    // Function to toggle between table and card views
    function toggleTableView() {
        const tableView = document.getElementById('deal_table');
        const cardView = document.getElementById('deal_cards');

        // Determine if the table is currently visible
        const isTableVisible = tableView.style.display !== 'none';

        // Update the display property of both views
        tableView.style.display = isTableVisible ? 'none' : 'block';
        cardView.style.display = isTableVisible ? 'block' : 'none';
    }
});

    </script>

  </body>

</html>