Project/config/routes.rb
Rails.application.routes.draw do


  root "games#index"
  get '/user', to: 'user#index'
  get 'games/search', to: 'games#search', as: :search_games
  get 'games/details/:id', to: 'games#details', as: :details_game
  get 'games/store_lowest_prices', to: 'games#store_lowest_prices'
  get '/collections', to: 'collections#index'
  post 'games/add_to_collection', to: 'games#add_to_collection', as: :add_to_collection_game


  get '/my_comments', to: 'user#user_comments', as: 'user_comments'

 #  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'


 # support page routes 
  # Add a route for the new action (displaying the contact form)
  get '/support', to: 'support#new', as: :new_support

  # Add a route for the create action (processing the form submission)
  post '/support', to: 'support#create', as: :create_support


  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }  


  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end 

  resources :deals

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
  end

  resources :collections, only: [:index, :new, :create, :destroy]

  resources :game_collections, only: [:create, :destroy] 

  resources :games do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
    member do
      post 'add_to_collection'
    end
  end

  namespace :admins do
        resources :users, only: [:index, :destroy] do 
         member do
      put 'ban'
      put 'unban'
      put 'temporary_ban'
      put 'make_admin'
      put 'revoke_admin'
    end
  end
    get 'index', to: 'users#index', as: :index
    get 'destroy', to: 'users#destroy', as: :destroy
    end
end

Project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
  # Devise modules
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable , :omniauthable, omniauth_providers:  %i[facebook google_oauth2 ] #steam github
  
  validates :password, presence: true, if: -> { password.present? }, confirmation: true



  before_create :set_default_role
  after_create :create_wishlist_collection

  # Create a new collection for the user
  def create_wishlist_collection
    Collection.create(user: self, name: 'My Wishlist')
  end


  # This ensures that new users have a default role of "user" unless explixity said that they are "admins"
  def set_default_role
    self.role ||= 'user'
  end
 
  #check if user is admin or not
  def admin?
    role == 'admin'
  end

  ## Collections
  has_many :collections,dependent: :destroy

  ## Comments
  has_many :comments,dependent: :destroy 

  
  ##...Avatar Attachment...##
  has_one_attached :avatar

  ## Validations
     validates :avatar, file_size: { less_than_or_equal_to: 5.megabytes },
                file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }
  


  def registered_with_email?
    provider.blank? # Assuming 'provider' is the attribute indicating the authentication provider
  end

  # Omniauth modules

  def self.from_omniauth(auth)
      user = User.where(email: auth.info.email).first
      puts "------------------------------------"
      puts auth.info.mail
      user ||= User.create!(provider: auth.provider, uid: auth.uid, email: auth.info.email, password: Devise.friendly_token[0, 20])
      user
    end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  
  
  def password_required?
    false
   end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
  
  def has_no_password?
    self.encrypted_password.blank?
  end


end

Project/app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        if current_user.admin?
          @users = User.all
          render 'admins/index'
        else
          flash[:alert] = "You do not have permission to access this page."
          redirect_to root_path
        end
    end
      
    #User-elimination
    def destroy
      puts "Params: #{params.inspect}"
      @user = User.find(params[:id])
      if @user.destroy
      # Send an email to the user using your mailer
      UserMailer.account_deleted_notification(@user.email).deliver_now

      redirect_to admins_index_path, notice: 'User was successfully deleted.'
    else
      redirect_to admins_index_path, alert: 'Failed to delete the user.'
    end
    end
    
    #Perma-Ban
    def ban
      puts "Params: #{params.inspect}"
      @user = User.find(params[:id])
      @user.update(banned: true, ban_until: nil)
      UserMailer.account_permabanned_notification(@user.email).deliver_now
      redirect_to admins_index_path, notice: 'User banned successfully.'
    end

    #admin can choose the duration of a ban
    def temporary_ban
      @user = User.find(params[:id])
      duration = params[:duration].to_i.days
      @user.update(banned: true, ban_until: Time.current + duration)
      UserMailer.account_tempban_notification(@user.email, Time.current + duration).deliver_now
      redirect_to admins_index_path, notice: "User temporarily banned successfully"
    end
    
    #admin can manually unban users
    def unban
      puts "Params: #{params.inspect}"
      @user = User.find(params[:id])
      @user.update(banned: false, ban_until: nil)
      UserMailer.account_unban_notification(@user.email).deliver_now
      redirect_to admins_index_path, notice: 'User unbanned successfully.'
    end

    #amdins can give to other users admins privlieges 
    def make_admin
      @user = User.find(params[:id])
      @user.update(role: 'admin')
      UserMailer.account_makeadmin_notification(@user.email).deliver_now
      redirect_to admins_index_path, notice: 'User is now an admin.'
    end
    
    #admins can revoke admins privileges to others
    def revoke_admin
      @user = User.find(params[:id])
      @user.update(role: 'user')
      UserMailer.account_revokeadmin_notification(@user.email).deliver_now
      redirect_to admins_index_path, notice: 'Admin is now a user.'
    end
    
      private
    #only admin can use these methods
      def authenticate_admin
        redirect_to root_path unless session[:admin_signed_in]
      end
      

end

Project/app/controllers/user_controller.rb
class UserController < ApplicationController
  layout 'layouts/navbar_layout'
  include SharedHelper
  # POST /users or /users.json
  before_action :authenticate_user!
  before_action :set_api_key
  
def create
  @user = User.new(user_params)

  respond_to do |format|
    if @user.save
      ApplicationMailer.with(user: @user).welcome_email.deliver_now

      format.html { redirect_to @user, notice: 'User was successfully created.' }
      format.json { render json: @user, status: :created, location: @user }
    else
      format.html { render action: 'new' }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

def set_api_key
  @api_key = 'b14274e8092bc14e227b32e4b66c2903bf4419c9'
end

def panel
  if current_user.admin?
    @users = User.all
    render 'admins/panel'
  else
    flash[:alert] = "You do not have permission to access this page."
    redirect_to root_path
  end
end

  def show
    @user = current_user
  end

  def index
    @user = current_user
    @collections = @user.collections
  end


  def user_comments
    @user_comments = current_user.comments
  end

  def destroy
    @user = current_user
    Comment.where(user_id: @user.id).destroy_all # Delete associated comments
    Collections.where(user_id: @user.id).destroy_all
    if @user.destroy
    redirect_to root_path, notice: 'Account deleted successfully.'
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
  end
end

Project/app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

Project/app/controllers/users/omniauth_callbacks_controller.rb
  class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    before_action :set_mapping


    def self.from_omniauth(auth)
      Rails.logger.debug "OmniAuth Data received: #{auth.inspect}"
  
      return unless auth
  
      user = User.where(email: auth.dig('info', 'email')).first
  
      if user
        Rails.logger.debug "User found by email: #{user.email}"
        user.update(provider: auth.provider, uid: auth.uid) if user.provider.nil? || user.uid.nil?
      else
        Rails.logger.debug "Creating a new user with OmniAuth data"
        user = User.create!(
          provider: auth.provider,
          uid: auth.uid,
          email: auth.dig('info', 'email') || auth.dig('info', 'user_info', 'email'), # Adjust the key based on provider
          password: Devise.friendly_token[0, 20]
        )
      end
    end


    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username)
    end

  
    def facebook
      @user = User.from_omniauth(request.env['omniauth.auth'])
      @user.username = request.env["omniauth.auth"].info.name if @user.username.blank?
      if @user.persisted?
        

        sign_in_and_redirect @user, event: :authentication, notice: "A confirmation E-mail has been sent to you"   
        set_flash_message(:notice, :success, kind: 'Facebook') if     is_navigational_format?
      else
        session['devise.facebook_data'] =  request.env['omniauth.auth'].except(:extra) 
        redirect_to new_user_registration_url
      end
    end
    
    
    def failure
      redirect_to root_path
    end
  
    
    

    def google_oauth2
      auth = request.env['omniauth.auth']
    # Find or create the user by email
    @user = User.find_or_initialize_by(email: auth.info.email)
    @user.username = request.env["omniauth.auth"].info.name if @user.username.blank?
    # Set username only for users registered with email (not via Google)
    unless @user.persisted?
      @user.username = auth.info.name.parameterize # You can adjust the logic to generate a username
      @user.password = Devise.friendly_token[0, 20]
      @user.save
      
    end
   
    sign_in_and_redirect @user, event: :authentication
    flash[:alert] = "Authentication via Google successful"
    

  end
=begin
THIS ARE METHODS FOR GITHUB AND STEAM, UNUSED 

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


      def steam
      if request.env['omniauth.auth'].present?
        Rails.logger.debug "OmniAuth Data: #{request.env['omniauth.auth'].inspect}"
        @user = User.from_omniauth(request.env['omniauth.auth'])
        puts 'Start'
        puts @user
        puts 'End'
        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "Steam") if is_navigational_format?
        else
          session["devise.steam_data"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      else
        # Handle the case where omniauth.auth is nil
        redirect_to root_path, alert: "Authentication data not received from Steam."
      end
    end
    
=end
  private

  def set_mapping
    request.env["devise.mapping"] = Devise.mappings[:user]
  end
end

Project/app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    
    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message!(:notice, flash_message)
      sign_in(resource_name, resource)
      respond_with resource, location: after_resetting_password_path_for(resource)
    else
      respond_with(resource)
    end
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end

  private

end

Project/app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!, only: [:edit, :update]

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation, :avatar, :description, :role)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :avatar, :description)}
  end
  

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :avatar, :description)
  end

  def update
    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)
    logger.debug("Account update params: #{account_update_params.inspect}")
    
    @user = current_user


    ##i think this mehtod is useless, should be checked
    if needs_password?
      successfully_updated = @user.update_with_password(account_update_params)
    else
      # Remove password-related fields for non-password updates

      account_update_params.delete('current_password')

      # Update the user with the modified parameters
      successfully_updated = @user.update(account_update_params)
    end

    if successfully_updated
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def edit
    super
  end

  private

  def needs_password?
    @user.email != params[:user][:email] || params[:user][:current_password].present?
  end
end

Project/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::Sessions::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  def destroy
    # Custom code here, if needed.

    # Call the Devise sign_out method to handle the logout logic.
   super
  end
  def create
    auth = request.env['omniauth.auth']
  end
  
  

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

Project/app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::Sessions::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

Project/app/helpers/user_helper.rb
module UserHelper
end

Project/app/views/user/index.html.erb
<head>
  <%= javascript_include_tag 'activestorage' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'profile', media: 'all' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
</head>

<!-- FLASH MESSAGES/ALERT -->
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<div class="profile-container">
  <!-- Left Column (30% of total width) -->
  <div class="profile-left-column">
    <h2>Your Account</h2>

    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, class: "rounded-circle profile-picture", size: "100x100" %>
    <% else %>
      <%= image_tag("user.jpg", alt: "User Image", class: "rounded-circle profile-picture", size: "100x100") %>
    <% end %>
    <p><strong>Username:</strong> <%= current_user.username %></p>
    
    <%= link_to 'Edit Profile', edit_user_registration_path(current_user), class: 'profile-button', id:"Edit Profile" %>
    <br><br>
    <%= link_to 'Show My Comments', user_comments_path, class: 'profile-button' %>
  </div>

  <!-- Right Column (70% of total width) -->
  <div class="profile-right-column">
    <h2>Account Overview</h2>
    <ul>
      <li><strong>Username:</strong> <%= current_user.username %></li>
      <li><strong>Email:</strong> <%= current_user.email %></li>
      <li><strong>Description:</strong> <% if current_user.description.present? %><%= current_user.description %><% else %> You can add a Description through Edit Profile button! <% end %> </li>
    </ul>
  </div>
</div>
<hr class="separator">
<div class="profile-container">
  <div class="wishlist">
    <h1 style="align: center"> <h2>Your Collections:</h2> <br><br>

    <% if @collections.present? %>
      <% @collections.each do |collection| %>
        <div>
          <div class="mb-4">
            <h3 style="padding-left: 10px;"><%= collection.name %></h3><br>
            <% games_in_collection = GameCollection.where(collection_id: collection.id).pluck(:game_id) %>
            <% if games_in_collection.present? %>
              <div id="<%= "collectionCarousel_#{collection.id}" %>" class="carousel slide mx-auto position-relative" style="width: 90%;" data-bs-interval="false">
                <div class="carousel-inner">
                  <% games_in_collection.each_slice(3).with_index do |games_batch, index| %>
                    <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
                      <div class="row">
                        <% games_batch.each do |game_plain| %>
                          <% game_info = game_info(game_plain) %>
                          <% prices = get_game_prices(game_plain) %>
                          <div class="col">
                            <div class="card">
                              <% if game_info['assets'].present? && game_info['assets']['banner400'].present? %>
                                <%= image_tag(game_info['assets']['banner400'], class: 'img-fluid') %>
                              <% else %>
                                <%= image_tag(image_path('placeholder.png'), class: 'img-fluid') %>
                              <% end %>
                              <div class="card-body">
                                <h5 class="card-title"><%= game_info['title'] %></h5>

                                <% prices.each do |price| %>
                                  <% first_deal = price['deals'].first %>
                                  <p class="card-text text-center">
                                    <del><%= "%.2f" % first_deal['regular']['amount'].to_f %> <%= first_deal['price']['currency'] %></del>
                                    <% if first_deal['price']['amount'] == 0 %>
                                      <span class="price-new fw-bold fs-3 text-success"><%= "%.2f" % first_deal['price']['amount'].to_f %> <%= first_deal['price']['currency'] %></span>
                                      <span class="badge bg-success">Free</span>
                                    <% elsif first_deal %>
                                      <span class="price-new fw-bold fs-3"><%= "%.2f" % first_deal['price']['amount'].to_f %> <%= first_deal['price']['currency'] %></span>
                                    <% else %>
                                      <p>No price information available</p>
                                    <% end %>
                                    <span class="discounted-price fw-bold fs-6">-<%= first_deal['cut'] %>%</span>
                                  </p>
                                <% end %>

                                <br>
                                <%= link_to "Details", details_game_path(id: game_plain), class: "btn profile-button" %>
                                <%= button_to raw('<i class="fas fa-times"></i>'), { controller: 'game_collections', action: 'destroy', id: collection.id, game_id: game_plain }, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure you want to delete this game from your collection?" }, 
                                  method: :delete, class: "btn btn-delete" %>
                              </div>
                            </div>
                          </div>
                        <% end %>
                        <% (3 - games_batch.size).times do %>
                          <div class="col"></div>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="<%= "#collectionCarousel_#{collection.id}" %>" data-bs-slide="prev" style="left: -12%;">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="<%= "#collectionCarousel_#{collection.id}" %>" data-bs-slide="next" style="right: -12%;">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            <% else %>
              <p>No games in this collection.</p>
            <% end %><br>
            <% if collection.name != "My Wishlist" %>
              <%= button_to 'Delete Collection', collection, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
            <% end %>
            <br>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>You don't have any collections yet.</p>
    <% end %>

    <br>

    <!-- Button to trigger the modal -->
    <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#newCollectionModal">
      New Collection
    </button>

    <!-- Modal for the new collection form -->
    <div class="modal fade" id="newCollectionModal" tabindex="-1" aria-labelledby="newCollectionModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content custom-modal">
          <div class="modal-header">
            <h5 class="modal-title" id="newCollectionModalLabel">Create a New Collection</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <%= form_with(model: Collection.new, url: collections_path, remote: true, id: "newCollectionForm") do |form| %>
              <div class="mb-3">
                <%= form.label :name, 'Collection Name', class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control', required: true %>
              </div>
              <%= form.submit 'Save', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Project/app/views/user/user_comments.html.erb
<head>
  <%= javascript_include_tag 'activestorage' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'profile', media: 'all' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
</head>

<div class="profile-container">
  <!-- Left Column (30% of total width) -->
  <div class="profile-left-column">
    <h2>Your Account</h2>
    <% if current_user.avatar.present? %>
      <%= image_tag current_user.avatar, class: "rounded-circle profile-picture", size: "100x100" %>
    <% else %>
      <%= image_tag("user.jpg", alt: "User Image", class: "rounded-circle profile-picture", size: "100x100") %>
    <% end %>
    <p><strong>Username:</strong> <%= current_user.username %></p>
    <%= link_to 'Edit Profile', edit_user_registration_path(current_user), class: 'profile-button' %>
    <br><br>
    <%= link_to 'Go back', user_path(current_user), class: 'profile-button' %>
  </div>

  <!-- Right Column (70% of total width) -->
<div class="profile-right-column">
  <h2>My Comments</h2>
  <% if @user_comments.any? %>
    <ul class="list-unstyled">
      <% @user_comments.each do |comment| %>
        <li>
          <div class="card mb-3 position-relative">
            <div class="card-body p-3">
              <div class="d-flex align-items-center">
                <%= image_tag(current_user.avatar, class: "rounded-circle shadow-1-strong me-3 mb-4", size: "60x60") if current_user.avatar.present? %>
                <div>
                  <h6 class="text-white fw-bold mb-1">
                    <%= comment.user.username %>
                    <% game_info = game_info(comment.gameplain) %>
                    <% if game_info.present? %>
                      <span class="text-muted ms-2">about</span>
                      <%= game_info['title'] %>
                    <% end %>
                  </h6>
                  <p class="text-white mb-3 mt-2"><%= comment.body %></p>
                  <p class="text-muted mb-0"><%= time_ago_in_words(comment.created_at) %> ago</p>
                </div>
              </div>
            </div>
            <div class="card-footer position-absolute bottom-0 end-0">
              <% game_info = game_info(comment.gameplain) %>
              <% if game_info.present? %>
                <p class="mb-0">
                  <%= link_to "Details", details_game_path(id: comment.gameplain), class: 'btn profile-button btn-sm'%>
                </p>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No comments found.</p>
  <% end %>
</div>