Project/config/routes.rb
Rails.application.routes.draw do


  root "games#index"
  get '/user', to: 'user#index'
  get 'games/search', to: 'games#search', as: :search_games
  get 'games/details/:id', to: 'games#details', as: :details_game
  get 'games/store_lowest_prices', to: 'games#store_lowest_prices'
  get '/collections', to: 'collections#index'
  post 'games/add_to_collection', to: 'games#add_to_collection', as: :add_to_collection_game


  get '/my_comments', to: 'user#user_comments', as: 'user_comments'

 #  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'


 # support page routes 
  # Add a route for the new action (displaying the contact form)
  get '/support', to: 'support#new', as: :new_support

  # Add a route for the create action (processing the form submission)
  post '/support', to: 'support#create', as: :create_support


  get '/auth/facebook/callback', to: 'users/omniauth_callbacks#facebook'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }  


  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end 

  resources :deals

  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
  end

  resources :collections, only: [:index, :new, :create, :destroy]

  resources :game_collections, only: [:create, :destroy] 

  resources :games do
    resources :comments, only: [:index, :create, :edit, :destroy, :update]
    member do
      post 'add_to_collection'
    end
  end

  namespace :admins do
        resources :users, only: [:index, :destroy] do 
         member do
      put 'ban'
      put 'unban'
      put 'temporary_ban'
      put 'make_admin'
      put 'revoke_admin'
    end
  end
    get 'index', to: 'users#index', as: :index
    get 'destroy', to: 'users#destroy', as: :destroy
    end
end

Project/app/views/admins/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <title>Admin Panel</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'activestorage' %>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 0;
      background-color: #242424;
      color: #fff; 
    }
    .search {
      width: 100%;
      position: relative;
      display: flex;
      margin-left: 20px;
      left: 0;
      right: 0;
    }

    .searchTerm {
      width: 20%;
      border: 3px solid #C0504D;
      border-right: none;
      padding: 5px;
      border-radius: 5px 0 0 5px;
      outline: none;
    }

    .searchButton {
      border: 1px solid #C0504D;
      background: #C0504D;
      text-align: center;
      color: #fff;
      border-radius: 0 5px 5px 0;
      cursor: pointer;
      font-size: 15px;
    }

    h1 {
      text-align: center;
      color: #fff;
    }
    .alert {
      padding: 10px;
      margin: 10px 0;
      border: 1px solid #555; 
      background-color: #333; 
      color: #fff;
    }
    .button-container {
      text-align: center;
      margin: 20px 0;
    }
    .button-link {
      display: inline-block;
      padding: 10px 20px;
      background-color: #007bff;
      color: #fff;
      text-decoration: none;
      border-radius: 5px;
    }
  #userTable {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
  }

  #userTable th, #userTable td {
    padding: 10px;
    text-align: center;
    border-bottom: 2px solid #fff;
  }

  #userTable td.email {
    border-right: 2px solid #fff;
  }

  .profile-picture {
    border-radius: 50%;
  }


    .admin-actions {
      display: flex;
      gap: 10px;
    }
    
    /* BUTTON STYLES */
    .btn {
      padding: 8px 16px;
      border: none;
      cursor: pointer;
      color: #fff;
    }
    .btn-primary {
      background-color: #007bff;
      border: 1px solid #007bff;
      border-radius: 5px;
    }
    .btn-success {
      background-color: #28a745;
      border: 1px solid #28a745;
      border-radius: 5px;
    }
    .btn-danger {
      background-color: #dc3545;
      border: 1px solid #dc3545;
      border-radius: 5px;
    }
  </style>
</head>
<body>
  <h1>Admin Panel</h1>

  <!-- FLASH MESSAGES/ALERT -->
  <% flash.each do |type, msg| %>
    <div class="alert">
      <%= msg %>
    </div>
  <% end %>

  


  <!-- BUTTON LINK -->
  <div class="button-container">
    <%= link_to "GameSalesTracker", root_path, class: "button-link" %>
  </div>

<!-- SEARCHBAR -->
       <div class="search">
           <input type="text" id="search" name="search" placeholder="Enter username or email" class="searchTerm">
           <button onclick=searchUsers() class="searchButton" id="searchButton">
            <i class="fas fa-search"></i>
          </button>
        </div>
  
  <!-- USER LIST -->
  <table id="userTable">
    <thead>
      <tr>
        <th>Avatar</th>
        <th>Username</th>
        <th>Email</th>
        <th>Admin</th>
        <th>Destroy</th>
        <th>Temp Ban / Perma Ban</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id=<%user.email%>>
          <td>
            <% if user.avatar.present? %>
              <%= image_tag user.avatar, class: "profile-picture", size: "100x100" %>
            <% else %>
              <%= image_tag("user.jpg", alt: "User Image", class: "profile-picture", size: "100x100") %>
            <% end %>
          </td>
          <td><%= user.username.present? ? user.username : "Not Available" %></td>
          <td class="email"><%= user.email %></td>
          <td>
            <% unless current_user.admin? && current_user == user %>
              <% if user.admin? %>
                <%= button_to 'Revoke Admin', revoke_admin_admins_user_path(user), method: :put, data: { confirm: 'Are you sure you want to revoke admin privileges?' }, class: "btn btn-danger" %>
              <% else %>
                <%= button_to 'Make Admin', make_admin_admins_user_path(user), method: :put, data: { confirm: 'Are you sure you want to make this user an admin?' }, class: "btn btn-success" %>
              <% end %>
            <% end %>
          </td>
          <td>
            <% unless current_user.admin? && current_user == user %>
              <%= button_to "Destroy", admins_user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            <% end %>
          </td>
          <td>
            <% unless current_user.admin? && current_user == user %>
              <% if user.banned? %>
                <%= button_to 'Unban', unban_admins_user_path(user), method: :put, data: { confirm: 'Are you sure you want to unban this user?' }, class: "btn btn-success" %>
              <% else %>
                <%= form_tag temporary_ban_admins_user_path(user), method: :put do %>
                  <%= hidden_field_tag :id, user.id %>
                  <%= select_tag :duration, options_for_select([['1 week', 7], ['1 month', 30], ['6 months', 180]]) %>
                  <%= submit_tag 'Temporary Ban', class: 'btn btn-primary' %> 
                <% end %>
                <%= button_to 'PermaBan', ban_admins_user_path(user), method: :put, data: { confirm: 'Are you sure you want to ban this user?' }, class: "btn btn-danger" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!-- END OF USER LIST -->


    <!-- SEARCHBAR SCRIPT -->
<script>
  function searchUsers() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("search");
    filter = input.value.toUpperCase();
    table = document.getElementById("userTable");
    tr = table.getElementsByTagName("tr");

    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      td = tr[i].getElementsByTagName("td")[2];

      if (td) {
        txtValue = td.textContent || td.innerText;

        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }
</script>


</body>
</html>